add_newline = false
palette = "catppuccin_mocha"

format = """
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character\
"""

[palettes.catppuccin_mocha]
crust = "#11111b"
text = "#cdd6f4"
overlay0 = "#6c7086"
mauve = "#cba6f7"
lavender = "#b4befe"
peach = "#fab387"
green = "#a6e3a1"
yellow = "#f9e2af"
red = "#f38ba8"
sapphire = "#74c7ec"
teal = "#94e2d5"
sky = "#89dceb"

[username]
show_always = true
style_user = "bold fg:mauve"
format = "[$user](style) → "

[directory]
truncation_length = 3
format = "[$path](bold fg:text) → "

[git_branch]
symbol = ""
style = "bold fg:lavender"
format = "[$branch](style) → "
truncation_length = 15
truncation_symbol = "…"

[git_state]
disabled = false
style = "bold fg:peach"
format = "[$state( $progress_current of $progress_total)](style) → "
cherry_pick = "picking"
bisect = "bisecting"
merge = "merging"
rebase = "rebasing"
revert = "reverting"

[git_status]
format = "([$staged$modified$deleted$untracked$ahead_behind](bold fg:overlay0))"
staged = "[+$count](fg:green) "
modified = "[!$count](fg:yellow) "
deleted = "[-$count](fg:red) "
untracked = "[?$count](fg:sapphire) "
ahead = "[⇡$count](fg:teal) "
behind = "[⇣$count](fg:peach) "
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](fg:mauve) "

[fill]
symbol = " "

[cmd_duration]
disabled = false
style = "bold fg:overlay0"
format = "[$duration]($style)"
min_time = 2_000
show_milliseconds = false

[character]
success_symbol = "[❯](bold fg:sky)"
error_symbol = "[❯](bold fg:red)"
vimcmd_symbol = "[❯](bold fg:mauve)"
