#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr &
bspc config pointer_motion_interval 1
bspc config focus_follows_pointer true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color6"
bspc config active_border_color "$color6"
bspc config focused_border_color "$color6"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color6"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
